[tool.poetry]
name = "mtcli"
version = "0.22.1"
description = "Converte gráfico do MetaTrader 5 para texto"
authors = ["Valmir Franca <vfranca3@gmail.com>"]
license = "BSD-3-Clause"
readme = "docs/README.md"
repository = "https://github.com/vfranca/mtcli"
documentation = "https://vfranca.github.io/mtcli/"
keywords = ["MetaTrader 5", "trading", "CLI"]
packages = [{include = "mtcli"}]

[tool.poetry.dependencies]
python = ">=3.8, <4"
click = "^8.0.3"
python-dotenv = "^0.19"
numpy = "^1.24"
metatrader5 = "^5.0.43"

[tool.poetry.dev-dependencies]
mock = "^4.0.3"
pytest = "^6.2.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
mt = "mtcli.mt:mt"
