[tool.poetry]
name = "chartcli"
version = "0.4.4"
description = "Utilitário de linha de comando para leitura de gráficos do MetaTrader 5"
authors = ["Valmir Franca <vfranca3@gmail.com>"]
license = "MIT"
readme = "README.rst"
repository = "https://github.com/vfranca/chartcli"
documentation = "https://chartcli.readthedocs.io"
keywords = ["metatrader5", "trading"]
classifiers = [
"Development Status :: 2 - Pre-Alpha",
"Natural Language :: Portuguese",
]

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.0"
python-dotenv = "^0.10.3"

[tool.poetry.dev-dependencies]
sphinx = "^2.2.2"
pytest = "^5.3.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
mt = "chartcli.cli:cli"
bars = "chartcli.cli:bars"
sma = "chartcli.cli:sma"
ema = "chartcli.cli:ema"
atr = "chartcli.cli:atr"
fib = "chartcli.cli:fib"
