[tool.poetry]
name = "mtcli"
version = "0.5.0"
description = "Utilitario de linha de comando para leitura de graficos do MetaTrader 5"
authors = ["Valmir Franca <vfranca3@gmail.com>"]
license = "MIT"
readme = "docs/README.md"
repository = "https://github.com/vfranca/mtcli"
documentation = "https://mtcli.readthedocs.io"
keywords = ["metatrader5", "trading"]
classifiers = [
"Development Status :: 2 - Pre-Alpha",
"Natural Language :: Portuguese",
]

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.0"
python-dotenv = "^0.10.3"
pymql5 = "^1.2.0"

[tool.poetry.dev-dependencies]
pytest = "^5.3.2"

[tool.poetry.scripts]
mt = "mtcli.cli:cli"
bars = "mtcli.cli:bars"
sma = "mtcli.cli:sma"
ema = "mtcli.cli:ema"
atr = "mtcli.cli:atr"
fib = "mtcli.cli:fib"
buy = "mtcli.cli:buy"
sell = "mtcli.cli:sell"
positions = "mtcli.cli:positions"
cancel = "mtcli.cli:cancel"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
