[tool.poetry]
name = "mtcli"
version = "0.9.0"
description = "Ferramenta de linha de comando para leitura de graficos do MetaTrader 5 para deficientes visuais"
authors = ["Valmir Franca <vfranca3@gmail.com>"]
maintainers = ["Valmir Franca <vfranca3@gmail.com>"]
license = "GPL-2.0-only"
readme = "docs/README.md"
repository = "https://github.com/vfranca/mtcli"
documentation = "https://vfranca.github.io/mtcli/"
keywords = ["metatrader5", "trading"]
classifiers = [
"Development Status :: 2 - Pre-Alpha",
"Environment :: Console",
"Environment :: Win32 (MS Windows)",
"Intended Audience :: Financial and Insurance Industry",
"License :: OSI Approved :: GNU General Public License (GPL)",
"Natural Language :: Portuguese (Brazilian)",
"Operating System :: Microsoft :: Windows :: Windows 10",
"Programming Language :: Python :: 3.8",
"Topic :: Adaptive Technologies",
"Topic :: Office/Business :: Financial :: Investment"
]

[tool.poetry.dependencies]
python = "^3.8"
python-dotenv = "^0.10.3"
click = "^7.1.2"
PyMQL5 = "^1.2.1"

[tool.poetry.dev-dependencies]
mock = "^4.0.3"
pytest = "^6.2.2"
black = "^20.8b1"

[tool.poetry.scripts]
mt = "mtcli.cli:cli"
bars = "mtcli.cli:bars"
sma = "mtcli.cli:sma"
ema = "mtcli.cli:ema"
atr = "mtcli.cli:atr"
fib = "mtcli.cli:fib"
buy = "mtcli.cli:buy"
sell = "mtcli.cli:sell"
order = "mtcli.cli:orders"
position = "mtcli.cli:positions"
cancel = "mtcli.cli:cancel"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
